FROM solr
user root


# 安装中文分词
WORKDIR /opt/solr/server/solr-webapp/webapp/WEB-INF/lib
ADD ik-analyzer-solr5-5.x.jar .
ADD solr-analyzer-ik-5.1.0.jar .
WORKDIR /opt/solr/server/solr-webapp/webapp/WEB-INF
ADD ext.dic .
ADD stopword.dic .
ADD IKAnalyzer.cfg.xml .

user solr
WORKDIR /opt/solr

# 由于使用数据卷，目录权限被调整为root ,因此在启动时
ENTRYPOINT ["docker-entrypoint.sh"]
CMD solr-foreground && chown -R solr /var/solr/data
